version: "2"
services:
  bitcoind:
    build:
      context: ./core/0.17.0/
    #image: nicolasdorier/docker-bitcoin:0.17.0
    container_name: bitcoind
    environment:
      BITCOIN_EXTRA_ARGS: |
        bitcoin.active=1
        bitcoin.mainnet=1
        rpclisten=<your aws ip - have your firewall up!>:10009
        bitcoind.rpchost=<your aws ip - have your firewall up!>
        bitcoind.rpcuser=rpcuser
        bitcoind.rpcpass=rpcpass
        bitcoin.node=bitcoind
        bitcoind.zmqpubrawblock=tcp://bitcoind:28332
        bitcoind.zmqpubrawtx=tcp://bitcoind:28333
        autopilot.active=0
    expose:
      - "18332"
    ports:
      - "0.0.0.0:18333:18333"
    volumes:
      - "bitcoin_datadir:/data"

  # clightning_bitcoin:
  #   image: elementsproject/lightningd
  #   container_name: lightningd
  #   command:
  #     - --bitcoin-rpcconnect=bitcoind:8332
  #     - --bitcoin-rpcuser=rpcuser
  #     - --bitcoin-rpcpassword=rpcpass
  #     - --network=testnet
  #     - --alias=piezzo-clightning
  #     - --log-level=debug
  #   environment:
  #     EXPOSE_TCP: "true"
  #   expose:
  #     - "9735"
  #   ports:
  #     - "0.0.0.0:9735:9735"
  #   volumes:
  #     - "clightning_bitcoin_datadir:/root/.lightning"
  #     - "bitcoin_datadir:/etc/bitcoin"
  #   links:
  #     - bitcoind

  lnd_bitcoin:
    build:
      context: ./lnd/0.5.1-beta/
    #image: piezzo/lnd_bitcoin
    container_name: lnd
    environment:
      BITCOIN_EXTRA_ARGS: |
        bitcoin.active=1
        bitcoin.testnet=1
        rpclisten=0.0.0.0:10009
        bitcoind.rpchost=<your aws ip - have your firewall up!>:8332
        bitcoind.rpcuser=rpcuser
        bitcoind.rpcpass=rpcpass
        bitcoin.node=bitcoind
        bitcoind.zmqpubrawblock=tcp://bitcoind:28332
        bitcoind.zmqpubrawtx=tcp://bitcoind:28333
    expose:
      - "9735"
    ports:
      - "0.0.0.0:9735:9735"
    volumes:
      - "clightning_bitcoin_datadir:/root/.lnd"
      - "bitcoin_datadir:/etc/bitcoin"
    links:
      - bitcoind

volumes:
  bitcoin_datadir:
  clightning_bitcoin_datadir:
